---
# These steps are based on:
# https://research.cs.wisc.edu/htcondor/get/

- name: Install pre-requisites
  ansible.builtin.package:
    name:
      - procps-ng
    state: present

- name: Install pre-requisites in RHEL8+
  ansible.builtin.package:
    name:
      - dnf-plugins-core
    state: present
  when: ansible_distribution_major_version|int >= 8

- name: Install pre-requisites in RHEL10+
  ansible.builtin.package:
    name:
      - gnupg2
    state: present
  when: ansible_distribution_major_version|int >= 10

- name: Download EPEL GPG key
  ansible.builtin.get_url:
    url: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    owner: root
    group: root
    mode: "0644"

- name: Import EPEL GPG key
  ansible.builtin.command:
    cmd: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
  changed_when: false

- name: Add YUM repository for EPEL
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Download HTCondor GPG key
  ansible.builtin.get_url:
    url: https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-{{ htcondor_version }}-Key
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-HTCondor-{{ htcondor_version }}
    owner: root
    group: root
    mode: "0644"

- name: Import HTCondor GPG key
  ansible.builtin.command:
    cmd: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-HTCondor-{{ htcondor_version }}
  changed_when: false

- name: Add YUM repository for HTCondor
  ansible.builtin.yum:
    name: https://research.cs.wisc.edu/htcondor/repo/{{ htcondor_version }}/htcondor-release-current.el{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Enable extra repositories in RHEL8
  set_fact:
    repo_to_enable: "powertools"
  when: ansible_distribution_major_version|int == 8

- name: Enable extra repositories in RHEL9+
  set_fact:
    repo_to_enable: "crb"
  when: ansible_distribution_major_version|int >= 9

- name: Install condor via package manager
  ansible.builtin.yum:
    name:
      - condor
    state: present
    update_cache: true
    enablerepo: "{{ repo_to_enable }}"
